# Generated by Django 4.2 on 2024-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mobilemodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmodel',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت'),
        ),
    ]
