# Generated by Django 4.2 on 2024-08-20 07:43

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('sid', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد معین')),
                ('state', models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default='real', max_length=50, verbose_name='نوع مشارکت کننده')),
                ('firstname', models.CharField(max_length=50, verbose_name='نام')),
                ('lastname', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('fathername', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('code', models.CharField(max_length=10, verbose_name='کدملی')),
                ('ceoname', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدیرعامل')),
                ('company', models.CharField(max_length=100, verbose_name='نام تجاری/شرکت')),
                ('ncode', models.CharField(blank=True, max_length=11, null=True, verbose_name='شناسه ملی')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=11, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('postalcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'مشارکت کننده',
                'verbose_name_plural': 'مشارکت کنندگان',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sid', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد معین')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نمایشگاه')),
                ('price', models.CharField(max_length=20, verbose_name='قیمت')),
                ('value_added', models.CharField(max_length=10, verbose_name='ارزش افزوده')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ برگزاری')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'نمایشگاه',
                'verbose_name_plural': 'نمایشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('amount', models.CharField(max_length=20, verbose_name='مبلغ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customermodel', verbose_name='مشارکت کننده')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('state', models.CharField(choices=[('wait', 'در انتظار بررسی'), ('accept', 'قبول شده'), ('deny', 'رد شده')], default='wait', max_length=50, verbose_name='وضعیت')),
                ('area', models.IntegerField(default=0, verbose_name='متراژ')),
                ('rules', models.BooleanField(verbose_name='قوانین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customermodel', verbose_name='مشارکت کننده')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.exhibitionmodel', verbose_name='نمایشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('state', models.CharField(choices=[('check', 'چک بانکی'), ('cashe', 'نقدی'), ('deny', 'پوز بانکی')], default='deny', max_length=50, verbose_name='وضعیت')),
                ('amount', models.IntegerField(default=1000, verbose_name='مبلغ')),
                ('cardnumber', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره کارت/چک')),
                ('issuerbank', models.CharField(blank=True, max_length=150, null=True, verbose_name='بانک صادرکننده')),
                ('rrn', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره سند بانکی')),
                ('tracenumber', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره پیگیری')),
                ('digitalreceipt', models.CharField(blank=True, max_length=150, null=True, verbose_name='رسید دیجیتال')),
                ('respcode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد نتیجه تراکنش')),
                ('respmsg', models.CharField(blank=True, max_length=150, null=True, verbose_name='متن نتیجه تراکنش')),
                ('payload', models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیحات')),
                ('datepaid', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ و زمان تراکنش')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.invoicemodel', verbose_name='فاکتور')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customermodel', verbose_name='مشارکت کننده')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'پیغام',
                'verbose_name_plural': 'پیغام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MessageChangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('modified_date', models.DateTimeField(verbose_name='تاریخ تغییرات')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.messagesmodel', verbose_name='پیغام اصلی')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'پیغام ویرایش شده',
                'verbose_name_plural': 'پیغام\u200cهای ویرایشی',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('price', models.CharField(max_length=20, verbose_name='مبلغ')),
                ('area', models.IntegerField(default=0, verbose_name='متراژ')),
                ('value_added', models.IntegerField(default=0, verbose_name='ارزش افزوده')),
                ('discount', models.CharField(blank=True, max_length=20, null=True, verbose_name='تخفیف')),
                ('total_price', models.CharField(max_length=20, verbose_name='مبلغ نهایی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customermodel', verbose_name='مشارکت کننده')),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.exhibitionmodel', verbose_name='نمایشگاه')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.invoicemodel', verbose_name='فاکتور')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'اقلام فاکتور',
                'verbose_name_plural': 'اقلام فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='DocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('state', models.CharField(choices=[('wait', 'در انتظار بررسی'), ('accept', 'قبول شده'), ('deny', 'رد شده')], default='wait', max_length=50, verbose_name='وضعیت')),
                ('file', models.FileField(upload_to=crm.models.documents_directory_path, verbose_name='مدرک')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customermodel', verbose_name='مشارکت کننده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد')),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_user_modified', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.UniqueConstraint(fields=('digitalreceipt',), name='specdr'),
        ),
        migrations.AddConstraint(
            model_name='customermodel',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='comcode'),
        ),
        migrations.AddConstraint(
            model_name='customermodel',
            constraint=models.UniqueConstraint(fields=('sid',), name='specid'),
        ),
    ]
