# Generated by Django 4.2 on 2024-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='postcode',
            new_name='postalcode',
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='ceoname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='ncode',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شناسه ملی'),
        ),
    ]
