# Generated by Django 4.2 on 2024-08-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_invoicemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='state',
            field=models.CharField(choices=[('check', 'چک بانکی'), ('cashe', 'نقدی'), ('pos', 'پوز بانکی')], default='pos', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitemmodel',
            constraint=models.UniqueConstraint(fields=('exhibition', 'customer'), name='excus'),
        ),
    ]
