# Generated by Django 4.2 on 2024-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_documentsmodel_state_requestmodel_state_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customermodel',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='comcode'),
        ),
        migrations.AddConstraint(
            model_name='customermodel',
            constraint=models.UniqueConstraint(fields=('sid',), name='specid'),
        ),
    ]
