# Generated by Django 4.2 on 2024-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customermodel_comcode_customermodel_specid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='total_price',
            field=models.CharField(max_length=20, verbose_name='مبلغ نهایی'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='value_added',
            field=models.IntegerField(default=0, verbose_name='ارزش افزوده'),
        ),
    ]
