# Generated by Django 4.2 on 2024-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_messagechangemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechangemodel',
            name='modified_date',
            field=models.DateTimeField(verbose_name='تاریخ تغییرات'),
        ),
    ]
